version: "3"

services:
  http-demo:
    container_name: go-jaeger-http-demo
    build: ./src/http-demo
    volumes:
      - ./src/http-demo:/home/deploy/http-demo
    ports:
      - "6060:6060"
      - "6061:6061"
    privileged: true
    environment:
      - GOPROXY=https://goproxy.cn
    networks: 
      - default
  grpc-demo:
    container_name: go-jaeger-grpc-demo
    build: ./src/grpc-demo
    volumes:
      - ./src/grpc-demo:/home/deploy/grpc-demo
    ports:
      - "1010:1010"
      - "1011:1011"
    privileged: true
    environment:
      - GOPROXY=https://goproxy.cn
    networks: 
      - default
  jaeger-demo:
    container_name: go-jaeger-jaeger-demo
    build: ./jaeger-demo
    volumes:
      - ./jaeger-demo:/home/deploy/jaeger-demo
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "9411:9411"
    privileged: true
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks: 
      - default
networks: 
  default:
    external: 
      name: example_default